# fly.toml app configuration file generated for final-launch-broken-snowflake-8297 on 2025-03-08T23:16:38-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'final-launch-broken-edged-snowflake-8297'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '16gb'
  cpu_kind = 'shared'
  cpus = 2
